### ISSUE TITLE
Buttons overlap on line wrap

### ISSUE THREAD

**Issue by revad** [seisiuneer/abctools#1]
v Minor issue.
Whistle Tab overlaps Sheet Music button. See screenshot.
Samsung Galaxy Tab S6 Lite Firefox latest.
It's fine in landscape
(Do you want suggestions here?)
Dave (DaveRo)
![Screenshot_20230206_073025_Firefox](https://user-images.githubusercontent.com/3061165/216912611-5d04d668-4086-4d64-bab0-b8eefca9390a.jpg)

**Comment by seisiuneer** [comment]
Try it now... added flex css to the button groups, should now wrap the buttons

**Comment by revad** [comment]
It's OK on my tablet in portrait orientation now.
On my small phone the minimum width is set by the textarea box so that line of buttons doesn't wrap.
