### ISSUE TITLE
Swing factor feature

### ISSUE THREAD

**Issue by sensn** [seisiuneer/abctools#10]
Hello,
I am just starting to learn abcjs, and I am interested in the swing-feature.
Is it right that this is only implemented in your version of abcjs?
I#d like to use abc inside my obsidian-notes, there is a plugin for that but it seems like it doesn't support
the %swing 0.25 0 command.
I had a quick look at the repos package.json. it says   "abcjs": "6.2.2"

[package.json](https://github.com/abcjs-music/obsidian-plugin-abcjs/blob/main/package.json)

Is it possible to compile your version into the obsidian-plugin?
thanks

**Comment by seisiuneer** [comment]
Hi,Unfortunately, the swing feature depends on both my tools code as well as additions I made to my highly customized version of abcjs.Perhaps in the future Paul will want to figure out how best to incorporate it into the released version of abcjs, but for now it can't be used for any other tool.All the best,MichaelOn Apr 25, 2024, at 12:14 AM, sensn ***@***.***> wrote:﻿
Hello,
I am just starting to learn abcjs, and I am interested in the swing-feature.
Is it right that this is only implemented in your version of abcjs?
I#d like to use abc inside my obsidian-notes, there is a plugin for that but it seems like it doesn't support
the %swing 0.25 0 command.
I had a quick look at the repos package.json. it says   "abcjs": "6.2.2"

Is it possible to compile your version into the obsidian-plugin?
thanks
