### ISSUE TITLE
Ties across a bar played as two notes

### ISSUE THREAD

**Issue by gitonthescene** [seisiuneer/abctools#12]
First off, thank you for this amazing project.  I only discovered it a couple of days ago and am having a lot of fun with it.

I tried the following transcription with the [online tool](https://michaeleskin.com/abctools/abctools.html) and when I try to play the wav file it looks like the G sharp that crosses the bar is played as two notes rather than an extended single note.  It seems to be unrelated to indicated accidental on one side of the bar.

I have some programming experience so I might try to figure out what the issue is but I thought I'd post anyway so it doesn't get lost.

```
X:0
T:3 on E
K:E
K:clef=bass
Q:98
.E,,z .E,,z .E,,z .F,/.=G,/(^G,/|G,).E, .B,,z/.C,/ .=D,/.C,/.D,/.C,/ .D,/E,3/2
```
Thanks again

**Comment by seisiuneer** [comment]
X: 1
T: Tie demo
C: Traditional
R: Reel
M: 4/4
L: 1/8
Q: 1/2=90
K: Edor
%%stretchlast true
%%text Tied but doesn't play continously
(D2 D2 | D2 D2) |
%%text Tied and does play continously
D2-D2- | D2- D2 |

**Comment by seisiuneer** [comment]
> First off, thank you for this amazing project.  I only discovered it a couple of days ago and am having a lot of fun with it.
> 
> 
> 
> I tried the following transcription with the [online tool](https://michaeleskin.com/abctools/abctools.html) and when I try to play the wav file it looks like the G sharp that crosses the bar is played as two notes rather than an extended single note.  It seems to be unrelated to indicated accidental on one side of the bar.
> 
> 
> 
> I have some programming experience so I might try to figure out what the issue is but I thought I'd post anyway so it doesn't get lost.
> 
> 
> 
> ```
> 
> X:0
> 
> T:3 on E
> 
> K:E
> 
> K:clef=bass
> 
> Q:98
> 
> .E,,z .E,,z .E,,z .F,/.=G,/(^G,/|G,).E, .B,,z/.C,/ .=D,/.C,/.D,/.C,/ .D,/E,3/2
> 
> ```
> 
> Thanks again

This shows both non-playing parenthesis-based and playing hyphen-based style ties in ABC:

https://michaeleskin.com/abctools/abctools.html?lzw=BoLgBAjAUAKuMEsCmYAmSC2B7KBheATgIaoIAuCWAdkQDZQBK4DSS9AsuACwD0XUAGXAQeADigBFYTwBMAXgCcABigBpcAFFUWAlACkegM5kCSMgGMAFrSLGwJgK5J9eskgAeZMIiSowAIwcvbSRDKgByLwAHGwBPMHNqCiosB0NaWKgACgARGTA8sAAfAvy8gEpilzdPb2Q-Iio-EMMwGKJ4xKpk1PTMvIBaQeLSgdKqqCA&format=noten&ssp=10&name=Tie_demo&play=1

**Comment by seisiuneer** [comment]
X: 1
T: Tie demo
C: Traditional
R: Reel
M: 4/4
L: 1/8
Q: 1/2=90
K: Edor
%%stretchlast true
%%text Tied but doesn't play continously
(D2 D2 | D2 D2) |
%%text Tied and does play continously
D2-D2- | D2- D2 |

**Comment by seisiuneer** [comment]
From the ABC 2.1 spec about ties vs. slurs on notes of the same pitch:

![image](https://github.com/seisiuneer/abctools/assets/7969711/cbaa70af-c8a8-4d8f-bda9-5f510e137209)

**Comment by gitonthescene** [comment]
Thanks so much for the detailed explanation.  Sorry for the noise.  I'm clearly not very experienced with abc.

**Comment by seisiuneer** [comment]
No problem, I had the same confusion with them myself for a while.On Jun 12, 2024, at 2:53 AM, gitonthescene ***@***.***> wrote:﻿
Thanks so much for the detailed explanation.  Sorry for the noise.  I'm clearly not very experienced with abc.
