### ISSUE TITLE
Mediawiki page export

### ISSUE THREAD

**Issue by WolfgangFahl** [seisiuneer/abctools#14]
https://en.wikipedia.org/wiki/ABC_notation
shows an example how ABC notation may be integrated into Mediawiki pages.
Unfortunately the standard ABC notation results sometimes do not properly render in Mediawiki due to the limitations of https://raw.githubusercontent.com/lilypond/lilypond/refs/heads/master/scripts/abc2ly.py so simply 
wrapping into a **score** tag is sometimes not sufficient. I would hope there could be some tool support for finding out what works and what does not. 

```
<score lang="ABC">
X:1
T:The Legacy Jig
M:6/8
L:1/8
R:jig
K:G
GFG BAB | gfg gab | GFG BAB | d2A AFD |
GFG BAB | gfg gab | age edB |1 dBA AFD :|2 dBA ABd |:
efe edB | dBA ABd | efe edB | gdB ABd |
efe edB | d2d def | gfe edB |1 dBA ABd :|2 dBA AFD |]
</score>
```

**Comment by seisiuneer** [comment]
For something like this, you probably want to use abcjs or abc2svg directly. 

This is not a function of my tool.
