### ISSUE TITLE
url/short url service

### ISSUE THREAD

**Issue by WolfgangFahl** [seisiuneer/abctools#15]
I would be great to be able to share tunes via an url/short url service. Given  the SPAM/copyright followup issues i am not sure what the best way would be to achieve this feature - may be e.g. running the service in a local docker image?

**Comment by seisiuneer** [comment]
There is already share link URL support in the tool.

Click the "Share" button in the tool to generate a share link.

URL shortening is supported via TinyURL, but please get your own TinyURL API key and enter it on the Advanced Settings page,

Details on sharing is here:

https://michaeleskin.com/abctools/userguide.html#sharing_controls

and on TinyURL use here:

https://michaeleskin.com/abctools/userguide.html#shortening_abc_share_urls

**Comment by seisiuneer** [comment]
Additionally, the tool can export share link URLs for all the tunes in either CSV or JSON format:

https://michaeleskin.com/abctools/userguide.html#export_all_musicxml

If you just want images for all the tunes, that is also possible:

https://michaeleskin.com/abctools/userguide.html#export_all_images

If what you were trying to do is embed ABC playback on your website, then you should look into using abcjs or abc2svg directly. That is not a function of my tool.

Details on abcjs here:

https://www.abcjs.net

And on abc2svg here:

https://chiselapp.com/user/moinejf/repository/abc2svg/doc/trunk/README.md
